#pragma config(UserModel, "D:/Github/KWS-Maze-Bot/KWSMazeBot.h")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "KWSMazeBot.c"

task main()
{
	startTask(gyroTask);
	startTask(Display);
 while (true) {
   //insert maze code here

}
}
