#pragma config(Sensor, port5,  Gyro,           sensorVexIQ_Gyro)
#pragma config(Motor,  motor1,          LeftMotor,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor6,          RightMotor,    tmotorVexIQ, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
