#pragma config(UserModel, "KWSMazeBot.h")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "KWSMazeBot.c"

task gyroTask(){
	while (true){
		gyrodrift();
}}

task Display(){
	while(true){
		DisplayVars();
}}

task Data(){
	while(true){
		DataCollection();
}}
task main()
{

	setMotorBrakeMode(LeftMotor, motorBrake);
	setMotorBrakeMode(RightMotor, motorBrake);

	ProgFinnished = false;
	startTask(gyroTask);
	startTask(Display);
	startTask(Data);
	delay(500);
	playSound(soundHeadlightsOn);
	while (!ProgFinnished) {
		global_1 = getGyroHeading(Gyro); //series 1
		global_2 = gyroValue; // 2
		global_3 = gyroError; // 3
		global_5 = getMotorSpeed(RightMotor); //5
		global_6 = getMotorSpeed(LeftMotor); //6
		//insert MazeBot code here
		setTouchLEDRGB(LED, 0, 255, 255);
		while(!getTouchLEDValue(LED)) {
		}
		mazeBotDrive(75);
		delay(1000);
		mazeBotStop();
		delay(1000);
		setTouchLEDRGB(LED, 255, 0, 255);
		mazeBotDrive(-75);
		delay(1000);
		mazeBotStop();
		delay(1000);
		setTouchLEDRGB(LED, 255, 255, 0);
		mazeBotLeft(50);
		delay(1000);
		mazeBotRight(50);
		//Delay for Brake Test
		playSound(soundPowerOff2);
		displayTextLine(line4, "Please Test Wheels for motor brake");
		delay(4000);
		displayTextLine(line4, "Sys Check Complete");
		playSound(soundHeadlightsOff);
		delay(1000);
		//End of MazeBot Code
		ProgFinnished = true;
	}
}
